### ISSUE TITLE
Can't Short Url with Emoji

### ISSUE THREAD

**Issue by ShyzuuPlayz** [telepathics/yourls-emojis#10]
Heya @telepathics,

I got another issue about your plugin, your plugin is activated but it doesn't short my url with emoji same if i disable every plugins and enable only yours.

**Comment by telepathics** [comment]
@ShyzuuPlayz thanks! i'll carve out some time this weekend to tend to the project

**Comment by telepathics** [comment]
@ShyzuuPlayz can you give me the short url you were trying with ?

**Comment by ShyzuuPlayz** [comment]
return: https://surl.nezium.xyz/9z8PHGi4MZLCMxuQCJrUNmmYp+

but no emoji :/

**Comment by telepathics** [comment]
@ShyzuuPlayz sorry, should've specified, which emoji(s) were you trying with?

**Comment by ShyzuuPlayz** [comment]
um what you mean?

**Comment by telepathics** [comment]
**example:** intended link https://surl.nezium.xyz/😎🐹 returns -> https://surl.nezium.xyz/9z8PHGi4MZLCMxuQCJrUNmmYp

**Comment by telepathics** [comment]
😅 i'm not sure what you mean... maybe i can add this screenshot to the readme, but this is what it should look like when adding a new URL 
<img width="443" alt="Screenshot 2021-08-11 at 16 24 02" src="https://user-images.githubusercontent.com/11712178/129047069-2e1f08ce-8312-4a16-a239-ee5479cc0496.png">

**Comment by ShyzuuPlayz** [comment]
You should make an random emoji link like the plugin i said above :D

**Comment by ShyzuuPlayz** [comment]
with length configuration :)

**Comment by ShyzuuPlayz** [comment]
![image](https://user-images.githubusercontent.com/40460147/129091224-c5d1dcbd-4dba-445b-926a-c961e67272af.png)

![image](https://user-images.githubusercontent.com/40460147/129091339-99c031b8-c74e-4034-b3d2-bdf706c2b7c4.png)

**Comment by telepathics** [comment]
ohhh, interesting! i want to iron out all of the bugs before adding new features, but this is a cool idea, thanks!

**Comment by ShyzuuPlayz** [comment]
Nope it remove my old url :(

**Comment by ShyzuuPlayz** [comment]
Without/with my theme it is the same infinite loading :/

**Comment by ShyzuuPlayz** [comment]
![image](https://user-images.githubusercontent.com/40460147/129274109-5c642bf2-c4be-4ebd-81df-b41a382a9ccb.png)

It create it, but instant delete after and leave it without giving me the return 🤔

**Comment by ShyzuuPlayz** [comment]
when i add manually again all emoji it does an error 500

![image](https://user-images.githubusercontent.com/40460147/129274332-357c4beb-1448-4367-9d07-fa2b5fc50ab4.png)

**Comment by ShyzuuPlayz** [comment]
redirection broken, but wait i'll go see error.log

**Comment by ShyzuuPlayz** [comment]
Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '=' in 

maybe an mysql issue 🤔

**Comment by ShyzuuPlayz** [comment]
Nevermind fixed

**Comment by ShyzuuPlayz** [comment]
how i fixed it?

Plugin Making this issue: https://github.com/joshp23/YOURLS-Compliance

If you want to keep the plugin just go through your phpmyadmin or etc and go to yourls_flagged and

Structure > Stick Keyword, reason and addr > now press edit > Change interclassment to utf8mb4_general_ci and it will fix it :D
