### ISSUE TITLE
Unable to activate plugin

### ISSUE THREAD

**Issue by deeusus** [telepathics/yourls-emojis#6]
Warning: require_once(***/www/user/plugins/yourls-emojis/vendor/autoload.php): failed to open stream: No such file or directory in ***/www/user/plugins/yourls-emojis/plugin.php on line 11

YOURLS v 1.8.1

**Comment by telepathics** [comment]
hello! did you download the `telepathics-yourls-emojis.zip` file from the [recent release](https://github.com/telepathics/yourls-emojis/releases) ? this error means it's missing dependencies.

**Comment by deeusus** [comment]
Sorry for my inattention) I downloaded the latest release-the plugin was successfully activated.
